test

diff --git a/.github/workflows/fix-paths.yaml b/.github/workflows/fix-paths.yaml
--- a/.github/workflows/fix-paths.yaml
+++ b/.github/workflows/fix-paths.yaml
@@ -15,11 +15,14 @@ jobs:
 
       - name: Run Bash commands
         run: |
-          dirs2process=('./assets' './credits' './style-guide')
+          dirs2process=('/assets' '/credits' '/style-guide')
           for _dir in ${dirs2process[*]} ;do
             find . -type f -not -path "*/.git*" -exec sed -i "s|${_dir}|.${_dir}|g" {} +
           done
 
           for _dir in ${dirs2process[*]} ;do
-            grep -nr "${_dir}" --exclude-dir=.git --exclude-dir=.github || echo "Did not found/grep: ${_dir}"
+            ##grep -nr "${_dir}" --exclude-dir=.git --exclude-dir=.github || echo "Did not found/grep: ${_dir}"
+            grep -nrw '[^.]/assets' --exclude-dir='.git' --exclude-dir='.github'  && \
+              echo -e "\n\t🔴 Found/grep something in: ${_dir}"                   || \
+              echo -e "\n\t🟢 Did not found/grep: ${_dir}"
           done
